# Generated by Django 5.1.4 on 2025-05-01 19:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('total_quantity', models.IntegerField(default=1, help_text="Nombre total d'exemplaires de cette clé")),
                ('in_cabinet', models.IntegerField(default=0, help_text="Nombre de clés stockées dans l'armoire")),
                ('in_safe', models.IntegerField(default=0, help_text='Nombre de clés stockées dans le coffre')),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('editor', 'Éditeur'), ('visitor', 'Visiteur')], default='visitor', help_text="Détermine les permissions de l'utilisateur dans l'application", max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='owner_set', related_query_name='owner', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='owner_set', related_query_name='owner', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KeyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='Identifiant unique optionnel pour cet exemplaire spécifique', max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Bon', max_length=50)),
                ('location', models.CharField(choices=[('Cabinet', 'Cabinet'), ('Coffre', 'Coffre'), ('Utilisateur', 'Utilisateur')], default='Cabinet', max_length=50)),
                ('original_location', models.CharField(blank=True, default='', help_text="Localisation d'origine, pour restaurer après retour", max_length=50)),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('key_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='listings.keytype')),
            ],
            options={
                'unique_together': {('key_type', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='listings.team')),
            ],
        ),
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('key_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='listings.keyinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_assignments', to='listings.user')),
            ],
        ),
    ]
