# Generated by Django 5.1.4 on 2025-06-01 02:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Gestionnaire', 'verbose_name_plural': 'Gestionnaires'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('ASSIGN', 'Attribution'), ('UNASSIGN', 'Désattribution'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement de mot de passe'), ('PASSWORD_RESET', 'Réinitialisation de mot de passe'), ('BULK_DELETE', 'Suppression en masse')], max_length=20, verbose_name="Type d'action")),
                ('object_type', models.CharField(choices=[('USER', 'Utilisateur'), ('TEAM', 'Équipe'), ('KEYTYPE', 'Type de clé'), ('KEYINSTANCE', 'Instance de clé'), ('KEYASSIGNMENT', 'Attribution de clé'), ('OWNER', 'Propriétaire'), ('SYSTEM', 'Système')], max_length=20, verbose_name="Type d'objet")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('object_name', models.CharField(max_length=255, verbose_name="Nom de l'objet")),
                ('user_name', models.CharField(max_length=255, verbose_name='Nom utilisateur')),
                ('user_role', models.CharField(default='visitor', max_length=50, verbose_name='Rôle utilisateur')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('date_only', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('old_values', models.TextField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.TextField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('affected_users', models.TextField(blank=True, null=True, verbose_name='Utilisateurs affectés')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Historique des actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='listings_ac_timesta_46dd5a_idx'), models.Index(fields=['date_only'], name='listings_ac_date_on_e96767_idx'), models.Index(fields=['action_type'], name='listings_ac_action__4aefcf_idx'), models.Index(fields=['object_type'], name='listings_ac_object__493468_idx'), models.Index(fields=['user'], name='listings_ac_user_id_1df23a_idx')],
            },
        ),
    ]
