# Generated by Django 4.2.5 on 2023-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='firstname',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
