# Generated by Django 5.1.4 on 2025-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_user_firstname_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='location',
            field=models.CharField(choices=[('Armoire', 'Armoire'), ('Coffre', 'Coffre'), ('Utilisateur', 'Utilisateur')], default='Armoire', max_length=50),
        ),
    ]
