# Generated by Django 4.2.7 on 2024-09-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_keys_teams_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keys',
            new_name='Key',
        ),
    ]
