# Generated by Django 4.2.7 on 2024-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_keys_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='key',
            name='in_cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='in_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='initial_key_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='key',
            name='key_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='key',
            name='key_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='key',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='key',
            name='number',
            field=models.IntegerField(),
        ),
    ]
