# Generated by Django 4.2.5 on 2024-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_key_comments_key_in_cabinet_key_in_safe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='in_safe',
            field=models.IntegerField(),
        ),
    ]
