# Generated by Django 6.0 on 2026-02-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
