# Generated by Django 4.2.5 on 2024-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_key_in_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_available',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
