# Generated by Django 4.2.5 on 2024-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_key_key_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_used',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
