# Generated by Django 4.2.5 on 2024-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_key_key_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='initial_key_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
