# Generated by Django 4.2.5 on 2024-10-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_key_initial_key_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='initial_key_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_available',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
