# Generated by Django 4.2.5 on 2024-10-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_key_initial_key_number_alter_key_key_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='in_safe',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
