# Generated by Django 4.2.5 on 2024-10-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_key_in_safe_alter_key_key_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='keyname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
