# Generated by Django 4.2.5 on 2024-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_users_keyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('team', models.CharField(max_length=15)),
                ('keynumbers', models.CharField(max_length=15)),
                ('keyname', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
