# Generated by Django 4.2.5 on 2024-10-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_user_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keyname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='keynumbers',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='listings.key'),
        ),
    ]
