# Generated by Django 4.2.5 on 2024-10-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_remove_user_keyname_remove_user_keynumbers_user_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
