# Generated by Django 4.2.5 on 2024-10-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.AddField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='listings.user'),
        ),
        migrations.AlterField(
            model_name='key',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='key',
            name='in_safe',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='initial_key_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_available',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
