# Generated by Django 4.2.5 on 2024-10-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_user_key_key_owner_alter_key_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='listings.key'),
        ),
    ]
