# Generated by Django 4.2.5 on 2024-10-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.RemoveField(
            model_name='key',
            name='owner',
        ),
        migrations.AddField(
            model_name='key',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='keys', to='listings.user'),
        ),
    ]
