# Generated by Django 4.2.5 on 2024-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_remove_user_key_remove_key_owner_key_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.ManyToManyField(blank=True, related_name='users', to='listings.key'),
        ),
    ]
