# Generated by Django 4.2.5 on 2024-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_remove_key_owner_user_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
