# Generated by Django 4.2.5 on 2024-10-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_key_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
