# Generated by Django 4.2.5 on 2024-10-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_team_comment_team_firstname_team_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('team', models.CharField(default='', max_length=10)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='team',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
