# Generated by Django 4.2.5 on 2024-10-30 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_teammembers_remove_team_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='listings.team'),
        ),
    ]
