# Generated by Django 4.2.5 on 2024-11-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(default='', max_length=20),
        ),
    ]
