# Generated by Django 4.2.5 on 2024-11-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_user_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
