# Generated by Django 4.2.5 on 2024-11-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_alter_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keys',
        ),
        migrations.AddField(
            model_name='key',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='listings.user'),
        ),
    ]
