# Generated by Django 4.2.5 on 2024-11-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_remove_user_keys_key_assigned_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='listings.team'),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
