# Generated by Django 4.2.5 on 2024-11-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_delete_band_delete_listing_user_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='name',
        ),
    ]
