# Generated by Django 5.1.4 on 2025-01-22 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_rename_lastname_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
