# Generated by Django 5.1.4 on 2025-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_keyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KeyAssignment',
        ),
    ]
