# Generated by Django 5.1.4 on 2025-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_key_assigned_date_delete_keyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
