# Generated by Django 5.1.4 on 2025-04-24 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_key_assigned_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='Identifiant unique optionnel pour cet exemplaire spécifique', max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], default='Bon', max_length=50)),
                ('location', models.CharField(choices=[('Cabinet', 'Cabinet'), ('Coffre', 'Coffre'), ('Utilisateur', 'Utilisateur')], default='Cabinet', max_length=50)),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('total_quantity', models.IntegerField(default=1, help_text="Nombre total d'exemplaires de cette clé")),
                ('in_cabinet', models.IntegerField(default=0, help_text="Nombre de clés stockées dans l'armoire")),
                ('in_safe', models.IntegerField(default=0, help_text='Nombre de clés stockées dans le coffre')),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_assignments', to='listings.user')),
                ('key_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='listings.keyinstance')),
            ],
        ),
        migrations.AddField(
            model_name='keyinstance',
            name='key_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='listings.keytype'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.AlterUniqueTogether(
            name='keyinstance',
            unique_together={('key_type', 'serial_number')},
        ),
    ]
