# Generated by Django 5.1.4 on 2025-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_keyinstance_keytype_keyassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinstance',
            name='original_location',
            field=models.CharField(blank=True, default='', help_text="Localisation d'origine, pour restaurer après retour", max_length=50),
        ),
    ]
