version: "3.8"

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: merchex.settings_nas

      MYSQL_HOST: merchex-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: merchex
      MYSQL_USER: merchex
      MYSQL_PASSWORD: password

      # Comme la DB existe déjà, évite de recharger data.json
      SKIP_LOADDATA: "1"

      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@egliseevangeliqueparis12.org
      DJANGO_SUPERUSER_PASSWORD: "password"
    networks:
      - merchex_net

networks:
  merchex_net:
    external: true
    name: merchex_net
